### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by dregad**
Dokuwiki log files shows

- require(action.php) is deprecated. It was called from require() in .../lib/plugins/htmlmetatags/action.php:14 Autoloading should be used instead!
- require(syntax.php) is deprecated. It was called from require() in .../lib/plugins/htmlmetatags/syntax/syntax.php:16 Autoloading should be used instead!

### CODE REVIEW

**Comment by dregad** [comment]
Hello @heikoS2C, my DokuWiki deprecated log is swamped with the above-mentioned messages, it would be great if you could merge this PR to fix them.

**Comment by heikoS2C** [comment]
Ok, I merge this tomorrow....Am 19.08.2023 13:39 schrieb Damien Regad ***@***.***>:
Hello @heikoS2C, my DokuWiki deprecated log is swamped with the above-mentioned messages, it would be great if you could merge this PR to fix them.

**Comment by dregad** [comment]
Thanks a lot ! Looking forward to it

**Comment by heikoS2C** [comment]
Sorry! I had no time on weekend because I was not in the near of my computer/office. Tomorrow I take time for this.With best regardsHeikoAm 20.08.2023 18:27 schrieb Damien Regad ***@***.***>:
Thanks a lot ! Looking forward to it

**Comment by dregad** [comment]
Thanks @heikoS2C I updated the plugin page https://www.dokuwiki.org/plugin:htmlmetatags to inform about the new version, looks like you forgot

**Pull request merged**
