### PR TITLE
Fix PHP 8 warnings (#6)

### PR DESCRIPTION
**Pull request by dregad**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@heikoS2C: Can you look this @dregad PR?

It solves one ticket about PHP 8+.

At this time, it is important to have PHP 8.1+.
- https://www.php.net/supported-versions.php

Thanks in advance.

**Comment by heikoS2C** [comment]
Many thanks, I will check this evening.Bye HeikoAm 20.08.2024 01:25 schrieb Neustradamus ***@***.***>:
@heikoS2C: Can you look this @dregad PR?
It solves one ticket about PHP 8+.
At this time, it is important to have PHP 8.1+.
https://www.php.net/supported-versions.php
Thanks in advance.

**Comment by Neustradamus** [comment]
@heikoS2C: Thanks!

Can you look tickets too: https://github.com/heikoS2C/htmlmetatags/issues?

@dregad: https://www.dokuwiki.org/plugin:htmlmetatags can be updated?

**Comment by dregad** [comment]
> @dregad: https://www.dokuwiki.org/plugin:htmlmetatags can be updated?

Yes it can. Surely you are aware that it's an open wiki and you that are able to do it yourself, right ?

**Pull request merged**
